use crate::types::{AnalysisResult, Module, ModuleItem, ApiEndpoint, AnalysisStats, CrossReference};
use serde_json;
use std::fs;
use std::path::Path;
use anyhow::Result;

pub struct Generator<'a> {
    output_dir: &'a Path,
    result: &'a AnalysisResult,
}

impl<'a> Generator<'a> {
    pub fn new(output_dir: &'a Path, result: AnalysisResult) -> Self {
        Self { output_dir, result: &result }
    }

    pub fn generate_all(&self) -> Result<()> {
        fs::create_dir_all(self.output_dir)?;
        
        self.generate_index()?;
        self.generate_modules_index()?;
        self.generate_module_details()?;
        self.generate_api_docs()?;
        self.generate_architecture_graph()?;
        self.generate_statistics()?;
        self.generate_schemas()?;
        
        Ok(())
    }

    fn generate_index(&self) -> Result<()> {
        let project = &self.result.project;
        let stats = &self.result.statistics;

        let content = format!(
            r#"# {name}

{description}

## Project Info

- **Version**: {version}
- **Language**: {language}
- **License**: {license}
- **Repository**: {repo}
- **Authors**: {authors}

## Overview

This documentation was automatically generated by [Automated Document Synthesizer](https://github.com/EonHermes/automated-document-synthesizer).

## Documentation

- [Modules](modules.html) - {modules} modules, {items} items
- [API Reference](api.html) - {endpoints} endpoints
- [Architecture](graph.svg) - Dependency graph
- [Schemas](schemas.json) - Data schemas and types
- [Statistics](stats.json) - Analysis statistics

## Quick Stats

- Total files scanned: {files}
- Total lines of code: {lines}
- Documentation coverage: {coverage:.1}%

---

Generated on: {}
"#,
            name = project.name,
            description = project.description.as_deref().unwrap_or("No description"),
            version = project.version.as_deref().unwrap_or("N/A"),
            language = project.language,
            license = project.license.as_deref().unwrap_or("N/A"),
            repo = project.repository.as_deref().unwrap_or("N/A"),
            authors = if !project.authors.is_empty() { project.authors.join(", ") } else { "N/A".to_string() },
            modules = stats.total_modules,
            items = stats.total_items,
            endpoints = self.result.api_endpoints.len(),
            files = stats.total_files,
            lines = stats.total_lines,
            coverage = stats.doc_coverage,
        );

        fs::write(self.output_dir.join("index.md"), content)?;
        Ok(())
    }

    fn generate_modules_index(&self) -> Result<()> {
        let mut content = String::from("# Modules\n\n");
        content.push_str("| Module | Items | Documentation | Path |\n");
        content.push_str("|--------|-------|----------------|------|\n");

        for module in self.result.modules.values() {
            let has_docs = module.documentation.as_ref().map(|d| !d.trim().is_empty()).unwrap_or(false);
            let item_count = module.items.len();
            content.push_str(&format!(
                "| **{}** | {} | {} | `{}` |\n",
                module.name,
                item_count,
                if has_docs { "✅" } else { "❌" },
                module.path
            ));
        }

        fs::write(self.output_dir.join("modules.md"), content)?;
        Ok(())
    }

    fn generate_module_details(&self) -> Result<()> {
        for module in self.result.modules.values() {
            let mut content = format!(
                "# Module: {}\n\n",
                module.name
            );

            if let Some(docs) = &module.documentation {
                content.push_str(&format!("{}\n\n", docs));
            }

            content.push_str("## Items\n\n");

            if module.items.is_empty() {
                content.push_str("*No items found.*\n");
            } else {
                content.push_str("| Name | Kind | Visibility | Line |\n");
                content.push_str("|------|------|------------|------|\n");

                for item in &module.items {
                    let visibility = match item.visibility {
                        crate::types::Visibility::Public => "pub",
                        crate::types::Visibility::Private => "private",
                        crate::types::Visibility::Restricted(ref s) => &format!("pub({})", s),
                    };
                    
                    content.push_str(&format!(
                        "| `{}` | {:?} | {} | {} |\n",
                        item.name,
                        item.kind,
                        visibility,
                        item.line
                    ));
                }

                content.push_str("\n## Detailed Reference\n\n");
                for item in &module.items {
                    content.push_str(&format!("### `{}`\n\n", item.name));
                    
                    if let Some(sig) = &item.signature {
                        content.push_str(&format!("```\n{}\n```\n\n", sig));
                    }

                    if let Some(docs) = &item.documentation {
                        content.push_str(&format!("{}\n\n", docs));
                    }

                    if !item.attributes.is_empty() {
                        content.push_str("**Attributes:**\n\n");
                        for attr in &item.attributes {
                            content.push_str(&format!("- `{}`\n", attr));
                        }
                        content.push_str("\n");
                    }
                }
            }

            let filename = format!("{}.md", module.name.replace("::", "_"));
            fs::write(self.output_dir.join(filename), content)?;
        }

        Ok(())
    }

    fn generate_api_docs(&self) -> Result<()> {
        if self.result.api_endpoints.is_empty() {
            return Ok(());
        }

        let mut content = String::from("# API Reference\n\n");
        content.push_str("| Method | Path | Summary | File |\n");
        content.push_str("|--------|------|---------|------|\n");

        for endpoint in &self.result.api_endpoints {
            let summary = endpoint.summary.as_deref().unwrap_or("*No description*");
            content.push_str(&format!(
                "| `{}` | `{}` | {} | `{}:{}` |\n",
                endpoint.method,
                endpoint.path,
                summary,
                endpoint.source_file,
                endpoint.line
            ));
        }

        content.push_str("\n## OpenAPI Specification\n\n");
        let openapi = self.generate_openapi_spec()?;
        content.push_str(&format!("```json\n{}\n```", openapi));

        fs::write(self.output_dir.join("api.md"), content)?;
        Ok(())
    }

    fn generate_openapi_spec(&self) -> Result<String> {
        #[derive(serde::Serialize)]
        struct OpenApi {
            openapi: String,
            info: serde_json::Value,
            paths: serde_json::Map<String, serde_json::Value>,
        }

        let mut paths = serde_json::Map::new();

        for endpoint in &self.result.api_endpoints {
            let mut path_item = serde_json::Map::new();
            
            let mut operation = serde_json::Map::new();
            operation.insert("summary".to_string(), serde_json::Value::String(
                endpoint.summary.as_deref().unwrap_or("").to_string()
            ));
            operation.insert("description".to_string(), serde_json::Value::String(
                endpoint.description.as_deref().unwrap_or("").to_string()
            ));
            operation.insert("tags".to_string(), serde_json::Value::Array(
                endpoint.tags.iter().map(serde_json::Value::String).collect()
            ));

            if !endpoint.parameters.is_empty() {
                let mut params = Vec::new();
                for param in &endpoint.parameters {
                    params.push(serde_json::json!({
                        "name": param.name,
                        "in": param.location,
                        "required": param.required,
                        "schema": param.schema,
                        "description": param.description
                    }));
                }
                operation.insert("parameters".to_string(), serde_json::Value::Array(params));
            }

            if let Some(ref req) = endpoint.request_body {
                operation.insert("requestBody".to_string(), serde_json::json!({
                    "required": req.required,
                    "content": {
                        "application/json": {
                            "schema": req.schema
                        }
                    }
                }));
            }

            if !endpoint.responses.is_empty() {
                let mut responses = serde_json::Map::new();
                for resp in &endpoint.responses {
                    responses.insert(resp.status_code.clone(), serde_json::json!({
                        "description": resp.description,
                        "content": resp.schema.as_ref().map(|s| {
                            serde_json::json!({
                                "application/json": { "schema": s }
                            })
                        })
                    }));
                }
                operation.insert("responses".to_string(), serde_json::Value::Object(responses));
            }

            path_item.insert(endpoint.method.to_lowercase(), serde_json::Value::Object(operation));
            paths.insert(endpoint.path.clone(), serde_json::Value::Object(path_item));
        }

        let openapi = OpenApi {
            openapi: "3.0.3".to_string(),
            info: serde_json::json!({
                "title": self.result.project.name,
                "version": self.result.project.version.as_deref().unwrap_or("1.0.0"),
                "description": self.result.project.description.as_deref().unwrap_or(""),
            }),
            paths,
        };

        Ok(serde_json::to_string_pretty(&openapi)?)
    }

    fn generate_architecture_graph(&self) -> Result<()> {
        let dot = DependencyGraph::new(self.result).to_dot()?;
        fs::write(self.output_dir.join("graph.dot"), dot)?;
        Ok(())
    }

    fn generate_statistics(&self) -> Result<()> {
        let stats_json = serde_json::to_string_pretty(&self.result.statistics)?;
        fs::write(self.output_dir.join("stats.json"), stats_json)?;
        Ok(())
    }

    fn generate_schemas(&self) -> Result<()> {
        if !self.result.schemas.is_empty() {
            let schemas_json = serde_json::to_string_pretty(&self.result.schemas)?;
            fs::write(self.output_dir.join("schemas.json"), schemas_json)?;
        }
        Ok(())
    }

    pub fn generate_changelog(&self) -> Result<()> {
        // Placeholder - will be implemented with git2
        Ok(())
    }
}
